core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('api/users/', views.api_users, name='api_users'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render

def index(request):
    users = User.objects.all()
    context = {'users': users}
    return render(request, 'index.html', context)

def api_users(request):
    users = User.objects.all()
    data = [{'username': user.username} for user in users]
    response = {'data': data}
    return JsonResponse(response)

core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="http://www.djangoproject.com/favicon.ico">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">

    {% block css %}{% endblock css %}
</head>

<body>
    {% include 'includes/nav.html' %}    
    <div class='container'>
         {% block content %}{% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="{% static 'core/js/myvue.js' %}"></script>

    {% block js %}{% endblock js %}

</body>

</html>

core/templates/includes/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://github.com/rg3915/django-vuejs-01-vue-inner-django" target="_blank">GitHub</a>
            </li>
        </ul>
    </div>
</nav>

core/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div id="app">
    <div class="jumbotron">
      <div class="container">
        <h1> Hola, mi nombre es Karlo y estoy combinando tecnologias. </h1>
         <p> Este proyecto trabaja con <a href="https://www.djangoproject.com/" target="_blank">Django</a> y <a href="https://vuejs.org/" target="_blank">VueJS</a>.</p>
        <p>
          <a href="https://github.com/settings/repositories" target="_blank">Visite mi cuenta en GitHub</a>
        </p>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <h3>Datos de Django 3</h3>
        <ul>
          {% for user in users %}
            <li>{{user}}</li>
          {% endfor %}
        </ul>
      </div>
      <div class="col">
        <h3>Datos de VueJS</h3>
        <ul>
          <li v-for='user in users'>${ user.username }</li>
        </ul>
      </div>
    </div>

  </div>

{% endblock content %}